/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#003ea8',
        'surface-dim': '#d2d9f4',
        'inverse-on-surface': '#eef0ff',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        'outline': '#737686',
        'secondary-fixed': '#6ffbbe',
        'surface-bright': '#faf8ff',
        'secondary-container': '#6cf8bb',
        'background': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c3c6d7',
        'on-tertiary-container': '#ffeedd',
        'surface-tint': '#0053db',
        'on-surface': '#131b2e',
        'on-background': '#131b2e',
        'primary-container': '#2563eb',
        'surface-container': '#eaedff',
        'secondary': '#006c49',
        'error': '#ba1a1a',
        'on-secondary-container': '#00714d',
        'tertiary-container': '#996100',
        'surface-container-high': '#e2e7ff',
        'surface-variant': '#dae2fd',
        'inverse-surface': '#283044',
        'on-primary-fixed': '#00174b',
        'surface-container-low': '#f2f3ff',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed': '#2a1700',
        'on-surface-variant': '#434655',
        'error-container': '#ffdad6',
        'primary': '#004ac6',
        'surface-container-highest': '#dae2fd',
        'primary-fixed': '#dbe1ff',
        'surface': '#faf8ff',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#002113',
        'tertiary': '#784b00',
        'on-primary-container': '#eeefff',
        'on-secondary-fixed-variant': '#005236',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#ffb95f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'gutter': '24px',
        'base': '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Literata', 'serif'],
        'body-lg': ['"Source Sans 3"', 'sans-serif'],
        'body-md': ['"Source Sans 3"', 'sans-serif'],
        'headline-sm': ['Literata', 'serif'],
        'label-sm': ['"Source Sans 3"', 'sans-serif'],
        'display-lg-mobile': ['Literata', 'serif'],
        'display-lg': ['Literata', 'serif'],
        'label-md': ['"Source Sans 3"', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
